name: Update Site

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create a tree of the repo
        run: tree . -H . -P '*.zip|*.html' -o index.html

      - name: Push changes to repo
        run: |
          git config user.name bulletproofpancake
          git config user.email 57520402+bulletproofpancake@users.noreply.github.com
          git add index.html
          git commit -m '${{ github.event.repository.updated_at}}'
          git push
